################################################################################
# EKS Dev Test Deployment
#
# > ⚠️ AI-Generated Deployment
# > Generated by Bob, an AI assistant powered by IBM watsonx.
# > Review before applying to production.
################################################################################

terraform {
  required_version = ">= 1.5.7"

  cloud {
    organization = "jose-merchan"
    workspaces {
      name = "eks-dev-test-vcs"
    }
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.35"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

data "aws_eks_addon_version" "ebs_csi_driver" {
  addon_name         = "aws-ebs-csi-driver"
  kubernetes_version = module.eks_cluster.cluster_version
  most_recent        = true
}

################################################################################
# EKS Cluster — private registry module
# NOTE: aws-ebs-csi-driver addon is excluded here; it is added below after
#       the OIDC provider is known (IRSA dependency ordering).
################################################################################

module "eks_cluster" {
  source  = "app.terraform.io/jose-merchan/eks-cluster/aws"
  version = "~> 0.0.4"

  # Mandatory tags
  environment = var.environment
  owner       = var.owner
  cost_center = var.cost_center
  project     = var.project

  # Cluster
  cluster_name       = "${var.project}-${var.environment}"
  kubernetes_version = "1.33"

  # Public endpoint enabled so HCP Terraform remote runner can reach the API server.
  # Restrict access to specific CIDRs in production.
  endpoint_public_access       = true
  endpoint_public_access_cidrs = ["0.0.0.0/0"]
  enable_irsa                  = true
  log_retention_days           = 90

  # Dev-sized single node group
  node_groups = {
    dev = {
      instance_types = ["t3.medium"]
      capacity_type  = "ON_DEMAND"
      min_size       = 1
      max_size       = 3
      desired_size   = 1
      disk_size_gb   = 50
    }
  }

  # New VPC — eu-central-1 has 3 AZs
  availability_zones     = ["${var.aws_region}a", "${var.aws_region}b", "${var.aws_region}c"]
  vpc_cidr               = "10.0.0.0/16"
  private_subnet_cidrs   = ["10.0.0.0/19", "10.0.32.0/19", "10.0.64.0/19"]
  public_subnet_cidrs    = ["10.0.128.0/20", "10.0.144.0/20", "10.0.160.0/20"]
  enable_internet_access = true
  single_nat_gateway     = true # single NAT saves cost in dev

  # Override addons: exclude aws-ebs-csi-driver — it is installed below
  # after the IRSA role has been created (dependency ordering fix)
  addons = {
    coredns    = { most_recent = true }
    kube-proxy = { most_recent = true }
    vpc-cni    = { most_recent = true, before_compute = true }
  }
}

################################################################################
# IRSA Role for EBS CSI Driver
# Must be created AFTER module.eks_cluster so the OIDC provider ARN is known.
# See: https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html
################################################################################

resource "aws_iam_role" "ebs_csi_driver" {
  name_prefix = "${var.project}-${var.environment}-ebs-csi-"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = {
        Federated = module.eks_cluster.oidc_provider_arn
      }
      Action = "sts:AssumeRoleWithWebIdentity"
      Condition = {
        StringEquals = {
          "${module.eks_cluster.oidc_provider}:sub" = "system:serviceaccount:kube-system:ebs-csi-controller-sa"
          "${module.eks_cluster.oidc_provider}:aud" = "sts.amazonaws.com"
        }
      }
    }]
  })

  tags = {
    Environment = var.environment
    Owner       = var.owner
    CostCenter  = var.cost_center
    Project     = var.project
    ManagedBy   = "Terraform"
  }
}

resource "aws_iam_role_policy_attachment" "ebs_csi_driver" {
  role       = aws_iam_role.ebs_csi_driver.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
}

# KMS permissions — required because node EBS volumes are encrypted with the cluster KMS key
resource "aws_iam_policy" "ebs_csi_driver_kms" {
  name_prefix = "${var.project}-${var.environment}-ebs-csi-kms-"
  description = "Allow EBS CSI driver to use the cluster KMS key for volume encryption"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "kms:CreateGrant",
        "kms:ListGrants",
        "kms:RevokeGrant",
        "kms:Encrypt",
        "kms:Decrypt",
        "kms:ReEncrypt*",
        "kms:GenerateDataKey*",
        "kms:DescribeKey"
      ]
      Resource = [module.eks_cluster.kms_key_arn]
    }]
  })

  tags = {
    Environment = var.environment
    Owner       = var.owner
    CostCenter  = var.cost_center
    Project     = var.project
    ManagedBy   = "Terraform"
  }
}

resource "aws_iam_role_policy_attachment" "ebs_csi_driver_kms" {
  role       = aws_iam_role.ebs_csi_driver.name
  policy_arn = aws_iam_policy.ebs_csi_driver_kms.arn
}

################################################################################
# EBS CSI Driver addon — installed after IRSA role is ready
################################################################################

resource "aws_eks_addon" "ebs_csi_driver" {
  cluster_name                = module.eks_cluster.cluster_name
  addon_name                  = "aws-ebs-csi-driver"
  addon_version               = data.aws_eks_addon_version.ebs_csi_driver.version
  resolve_conflicts_on_create = "OVERWRITE"
  resolve_conflicts_on_update = "OVERWRITE"
  service_account_role_arn    = aws_iam_role.ebs_csi_driver.arn
  preserve                    = false # false = EKS removes all addon resources on destroy

  namespace_config {
    namespace = "kube-system"
  }

  timeouts {
    create = "30m"
    update = "30m"
    delete = "30m"
  }

  tags = {
    Environment = var.environment
    Owner       = var.owner
    CostCenter  = var.cost_center
    Project     = var.project
    ManagedBy   = "Terraform"
  }

  depends_on = [
    module.eks_cluster,
    aws_iam_role_policy_attachment.ebs_csi_driver,
    aws_iam_role_policy_attachment.ebs_csi_driver_kms,
  ]
}

################################################################################
# Kubernetes provider — authenticates using the new cluster's outputs
################################################################################

provider "kubernetes" {
  host                   = module.eks_cluster.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks_cluster.cluster_certificate_authority_data)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args = [
      "eks", "get-token",
      "--cluster-name", module.eks_cluster.cluster_name,
      "--region", var.aws_region,
    ]
  }
}

################################################################################
# Test web application — NGINX served via AWS NLB (internet-facing)
################################################################################

resource "kubernetes_namespace" "test_app" {
  metadata {
    name = "test-app"
    labels = {
      environment = var.environment
      owner       = var.owner
      project     = var.project
    }
  }

  depends_on = [module.eks_cluster]
}

resource "kubernetes_deployment" "nginx" {
  metadata {
    name      = "nginx"
    namespace = kubernetes_namespace.test_app.metadata[0].name
    labels = {
      app         = "nginx"
      environment = var.environment
    }
  }

  spec {
    replicas = 2

    selector {
      match_labels = {
        app = "nginx"
      }
    }

    template {
      metadata {
        labels = {
          app         = "nginx"
          environment = var.environment
        }
      }

      spec {
        container {
          name  = "nginx"
          image = "public.ecr.aws/nginx/nginx:1.27-alpine"

          port {
            container_port = 80
          }

          resources {
            requests = {
              cpu    = "50m"
              memory = "64Mi"
            }
            limits = {
              cpu    = "100m"
              memory = "128Mi"
            }
          }

          # Custom welcome page that confirms the deployment is Bob-generated
          volume_mount {
            name       = "html"
            mount_path = "/usr/share/nginx/html"
          }
        }

        # Inline ConfigMap volume with custom HTML
        volume {
          name = "html"
          config_map {
            name = kubernetes_config_map.nginx_html.metadata[0].name
          }
        }
      }
    }
  }

  depends_on = [kubernetes_namespace.test_app]
}

resource "kubernetes_config_map" "nginx_html" {
  metadata {
    name      = "nginx-html"
    namespace = kubernetes_namespace.test_app.metadata[0].name
  }

  data = {
    "index.html" = <<-HTML
      <!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>EKS &#x2014; ${var.project}</title>
          <style>
            *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

            body {
              min-height: 100vh;
              display: flex;
              align-items: center;
              justify-content: center;
              font-family: 'IBM Plex Sans', 'Segoe UI', system-ui, sans-serif;
              background: linear-gradient(135deg, #0f0c29, #1a1a6e, #12003d);
              background-size: 400% 400%;
              animation: gradientShift 12s ease infinite;
              color: #f4f4f4;
              padding: 2rem;
            }

            @keyframes gradientShift {
              0%   { background-position: 0% 50%; }
              50%  { background-position: 100% 50%; }
              100% { background-position: 0% 50%; }
            }

            .card {
              background: rgba(255, 255, 255, 0.07);
              backdrop-filter: blur(18px);
              -webkit-backdrop-filter: blur(18px);
              border: 1px solid rgba(255, 255, 255, 0.15);
              border-radius: 20px;
              padding: 3rem 3.5rem;
              max-width: 560px;
              width: 100%;
              box-shadow: 0 25px 60px rgba(0, 0, 0, 0.5);
              text-align: center;
            }

            .badge {
              display: inline-flex;
              align-items: center;
              gap: 0.5rem;
              background: rgba(66, 220, 130, 0.15);
              border: 1px solid rgba(66, 220, 130, 0.4);
              color: #42dc82;
              border-radius: 999px;
              padding: 0.4rem 1.1rem;
              font-size: 0.85rem;
              font-weight: 600;
              letter-spacing: 0.04em;
              text-transform: uppercase;
              margin-bottom: 1.6rem;
            }

            .badge::before {
              content: '';
              width: 8px; height: 8px;
              border-radius: 50%;
              background: #42dc82;
              animation: pulse 1.8s ease-in-out infinite;
            }

            @keyframes pulse {
              0%, 100% { opacity: 1; transform: scale(1); }
              50%       { opacity: 0.4; transform: scale(1.4); }
            }

            h1 {
              font-size: 2rem;
              font-weight: 700;
              line-height: 1.2;
              margin-bottom: 0.5rem;
              background: linear-gradient(90deg, #ffffff, #a8c8ff);
              -webkit-background-clip: text;
              -webkit-text-fill-color: transparent;
              background-clip: text;
            }

            .subtitle {
              color: rgba(255,255,255,0.5);
              font-size: 0.95rem;
              margin-bottom: 2.2rem;
            }

            .info-grid {
              display: grid;
              grid-template-columns: 1fr 1fr;
              gap: 1rem;
              margin-bottom: 2rem;
            }

            .info-item {
              background: rgba(255,255,255,0.05);
              border: 1px solid rgba(255,255,255,0.1);
              border-radius: 12px;
              padding: 0.9rem 1rem;
              text-align: left;
            }

            .info-label {
              font-size: 0.72rem;
              font-weight: 600;
              letter-spacing: 0.08em;
              text-transform: uppercase;
              color: rgba(255,255,255,0.4);
              margin-bottom: 0.3rem;
            }

            .info-value {
              font-size: 0.95rem;
              font-weight: 600;
              color: #ffffff;
            }

            .divider {
              border: none;
              border-top: 1px solid rgba(255,255,255,0.1);
              margin: 0 0 1.5rem;
            }

            .footer {
              font-size: 0.78rem;
              color: rgba(255,255,255,0.35);
              line-height: 1.6;
            }

            .footer strong {
              color: #78a9ff;
              font-weight: 600;
            }

            .provider-logo {
              display: inline-block;
              margin-top: 1rem;
              background: rgba(255,255,255,0.06);
              border: 1px solid rgba(255,255,255,0.1);
              border-radius: 8px;
              padding: 0.35rem 0.9rem;
              font-size: 0.75rem;
              font-weight: 700;
              letter-spacing: 0.1em;
              color: #78a9ff;
              text-transform: uppercase;
            }
          </style>
        </head>
        <body>
          <div class="card">
            <div class="badge">Cluster Live</div>
            <h1>EKS Cluster is Ready</h1>
            <p class="subtitle">Amazon Elastic Kubernetes Service</p>

            <div class="info-grid">
              <div class="info-item">
                <div class="info-label">Environment</div>
                <div class="info-value">${var.environment}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Project</div>
                <div class="info-value">${var.project}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Region</div>
                <div class="info-value">${var.aws_region}</div>
              </div>
              <div class="info-item">
                <div class="info-label">Provider</div>
                <div class="info-value">AWS</div>
              </div>
            </div>

            <hr class="divider" />

            <div class="footer">
              Generated by <strong>Bob</strong><br/>
              IBM watsonx AI Assistant
              <div class="provider-logo">IBM &#x2022; watsonx</div>
            </div>
          </div>
        </body>
      </html>
    HTML
  }

  depends_on = [kubernetes_namespace.test_app]
}

# Internet-facing Network Load Balancer — exposes port 80 to the internet
resource "kubernetes_service" "nginx" {
  metadata {
    name      = "nginx"
    namespace = kubernetes_namespace.test_app.metadata[0].name
    annotations = {
      # AWS NLB (faster provisioning than Classic ELB)
      "service.beta.kubernetes.io/aws-load-balancer-type"   = "nlb"
      "service.beta.kubernetes.io/aws-load-balancer-scheme" = "internet-facing"
    }
  }

  spec {
    selector = {
      app = "nginx"
    }

    type = "LoadBalancer"

    port {
      port        = 80
      target_port = 80
      protocol    = "TCP"
    }
  }

  depends_on = [kubernetes_deployment.nginx]
}
